name: rsa_pkcs
version: 1.1.1
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: RSA,PKCS#1,PKCS#8
homepage: https://github.com/amaurel/rsa_pkcs

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  asn1lib: "^0.6.4"

dev_dependencies:
  test: "^1.0.0"
