name: rsa_pkcs
version: 0.1.2
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: RSA,PKCS#1,PKCS#8
homepage: https://github.com/amaurel/rsa_pkcs
dependencies:
  asn1lib: ">=0.4.1 <0.5.0"
  pointycastle: ">=0.10.0+1 <0.11.0"
dev_dependencies:
  test: any
